import Head from 'next/head';
import Image from 'next/image';
import Users from '../components/Users';
import styles from '../styles/Home.module.css';

export default function Home({users}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Users data={users} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


export async function getStaticProps(context) {
  const res = await fetch('http://localhost:5000/api/all-users');
  const data = await res.json();
  console.log(data);
  return {
    props: {
      users: data
    }, // will be passed to the page component as props
  }
}